const data = [
  {
    heading: "Incomplete",
    color: "#D21010",
    cards: [
      {
        clientPhoto: "./client.jpg", 
        clientName: "Client Name 1",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Todo",
    color: "blue",
    cards: [
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 4",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Incomplete",
    color: "#D21010",
    cards: [
      {
        clientPhoto: "./client.jpg", 
        clientName: "Client Name 1",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Todo",
    color: "blue",
    cards: [
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 4",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Incomplete",
    color: "#D21010",
    cards: [
      {
        clientPhoto: "./client.jpg", 
        clientName: "Client Name 1",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Todo",
    color: "blue",
    cards: [
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 3",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 4",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
  {
    heading: "Incomplete",
    color: "#D21010",
    cards: [
      {
        clientPhoto: "./client.jpg", 
        clientName: "Client Name 1",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
      {
        clientPhoto: "./client.jpg",
        clientName: "Client Name 2",
        profilePhoto: "./profile.jpeg",
        profileName: "Sadik Istiak",
        task: "lorem ipsum dolor sit amet,...",
        taskCount: "1/2",
        assignedPerson: [ "./client.jpg", "./profile.jpeg"],
        comments: 15,
        attachments: [{}],
        date: "30-12-2022",
      },
    ],
  },
];

export default data;